#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom cli cli_abort
#' @importFrom cli cli_h2
#' @importFrom cli cli_li
#' @importFrom cli cli_text
#' @importFrom cli col_magenta
#' @importFrom cli style_underline
#' @importFrom digest digest
#' @importFrom dplyr across
#' @importFrom dplyr add_row
#' @importFrom dplyr all_of
#' @importFrom dplyr everything
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr if_all
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr rows_upsert
#' @importFrom dplyr select
#' @importFrom dplyr select_if
#' @importFrom dplyr slice_tail
#' @importFrom dplyr summarise
#' @importFrom dplyr where
#' @importFrom extraDistr rdirichlet
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_line
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 expansion
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 geom_errorbar
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_violin
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 guide_legend
#' @importFrom ggplot2 guides
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_colour_manual
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 scale_y_discrete
#' @importFrom ggplot2 stat_density
#' @importFrom ggplot2 stat_summary
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 unit
#' @importFrom ggbeeswarm geom_beeswarm
#' @importFrom googlesheets4 read_sheet
#' @importFrom mc2d rpert
#' @importFrom miceadds sumpreserving.rounding
#' @importFrom openxlsx read.xlsx
#' @importFrom rlang .data
#' @importFrom rlang caller_env
#' @importFrom scales hue_pal
#' @importFrom stats median
#' @importFrom stats na.omit
#' @importFrom stats quantile
#' @importFrom stats setNames
#' @importFrom stringr str_split_1
#' @importFrom tibble as_tibble
#' @importFrom tibble remove_rownames
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tools file_ext
#' @importFrom utils read.csv
## usethis namespace: end
NULL
